# Write a function so that the columns of the output matrix are the power of the input vector. The order of the power is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wiseto the power of (N-i-1)

In [1]:
import numpy as np
def ATVanderMonde(x,n=0):
    if n is 0:
        n = len(x)
    List1 = []
    for data in x:
        for i in range(n):
            List1.append(data**(n-1-i))
    matrix = np.array(List1).reshape((len(x),n))
    return matrix

List = [1,2,3,4,5]
mat = ATVanderMonde(List,3)
#print(type(mat))
print(mat)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
